In [ ]:
from google.colab import files
uploaded=files.upload()

Saving jobss.csv to jobss.csv


In [ ]:
import pandas as pd
data = pd.read_csv('jobss.csv')
print(data.head())
print(data.columns)

                                           Job Title Job Experience Required  \
0                              Digital Media Planner              5 - 10 yrs   
1                           Online Bidding Executive               2 - 5 yrs   
2   Trainee Research/ Research Executive- Hi- Tec...               0 - 1 yrs   
3                                  Technical Support               0 - 5 yrs   
4                  Software Test Engineer -hyderabad               2 - 5 yrs   

                                          Key Skills   Location  \
0                      Media Planning| Digital Media     Mumbai   
1   pre sales| closing| software knowledge| clien...  Pune,Pune   
2   Computer science| Fabrication| Quality check|...    Gurgaon   
3                                  Technical Support     Mumbai   
4   manual testing| test engineering| test cases|...  Hyderabad   

                                     Functional Area  \
0  Marketing , Advertising , MR , PR , Media Plan...   
1   

In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Assuming 'df' is your DataFrame and 'column' is the categorical variable column name
encoder = OneHotEncoder()
encoded_data = encoder.fit_transform(data[['Job Title','Job Experience Required','Key Skills','Location','Functional Area','Industry','sal']])


In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Assuming 'y' is your target variable as a pandas Series
y=data['Role']
encoder = OneHotEncoder(sparse=False)
y_encoded = encoder.fit_transform(y.values.reshape(-1, 1))


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
# Assuming 'encoded_data' is the output of one-hot encoding
df_encoded = pd.concat([data, pd.DataFrame(encoded_data.toarray())], axis=1)


In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Assuming 'encoder' is your OneHotEncoder object and 'column_names' is the list of original column names
encoded_column_names = encoder.get_feature_names_out()
print(encoded_column_names)


['x0_Accounts Executive/Accountant' 'x0_Accounts Manager' 'x0_Architect'
 'x0_Area Sales Manager' 'x0_Associate/Senior Associate -(NonTechnical)'
 'x0_Associate/Senior Associate -(Technical)' 'x0_Business/EDP Analyst'
 'x0_CEO/MD/Director' 'x0_Centre Head / Branch Head / Club Manager'
 'x0_Client Servicing Executive' 'x0_Client Servicing/Key Account Manager'
 'x0_Content Developer' 'x0_Corporate Planning/Strategy Manager'
 'x0_Design Engineer' 'x0_ERP Consultant' 'x0_Engineering Manager'
 'x0_Functional Outside Consultant' 'x0_Graphic Designer'
 'x0_Graphic/Web Designer' 'x0_HR Executive'
 'x0_Head / VP/ GM/ National Manager After Sales'
 'x0_Head/VP/GM/National Manager -Sales' 'x0_Logistics Executive'
 'x0_Media Planning Executive/Manager' 'x0_Other'
 'x0_Pay Roll/Compensation Manager' 'x0_Process Flow Analyst'
 'x0_Project Architect' 'x0_Project Lead' 'x0_Project Manager-IT/Software'
 'x0_Quality Assurance/Quality Control Executive' 'x0_R&D Executive'
 'x0_Receptionist' 'x0_Recruitme

In [ ]:
# Assuming 'column' is the original categorical column name
df_encoded.drop('Job Title', axis=1, inplace=True)
df_encoded.drop('Job Experience Required', axis=1, inplace=True)
df_encoded.drop('Key Skills', axis=1, inplace=True)
df_encoded.drop('Location', axis=1, inplace=True)
df_encoded.drop('Functional Area', axis=1, inplace=True)
df_encoded.drop('Industry', axis=1, inplace=True)
df_encoded.drop('Role', axis=1, inplace=True)
df_encoded.drop('sal', axis=1, inplace=True)



In [ ]:
y=y_encoded
x=df_encoded
print(y)
print(x)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
     0    1    2    3    4    5    6    7    8    9    ...  446  447  448  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
108  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
109  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
110  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
111  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0 

In [ ]:
from sklearn.model_selection import train_test_split
train_X,val_X,train_Y,val_Y=train_test_split(x,y,test_size=0.30,random_state=6)

In [ ]:
print(train_X.shape)
print(train_Y.shape)
print(val_X.shape)
print(val_Y.shape)

(79, 456)
(79, 56)
(34, 456)
(34, 56)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(random_state=7,n_estimators=70)
model.fit(train_X,train_Y)

RandomForestClassifier(n_estimators=70, random_state=7)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(random_state=7)
model.fit(train_X,train_Y)


DecisionTreeClassifier(random_state=7)

In [ ]:
pred_Y=model.predict(val_X)
import sklearn.metrics as metrics
accuracy=metrics.accuracy_score(val_Y,pred_Y)
print("Accuracy: ",accuracy)

Accuracy:  0.5


In [ ]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

xgb_model = xgb.XGBClassifier()

# Fit the model to the training data
xgb_model.fit(train_X,train_Y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [ ]:
y_pred = xgb_model.predict(val_X)


import sklearn.metrics as metrics
accuracy=metrics.accuracy_score(val_Y,pred_Y)
print("Accuracy: ",accuracy)

Accuracy:  0.391304347826087


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

# Train the classifier
knn.fit(train_X,train_Y)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
from sklearn.metrics import accuracy_score
y_pred = knn.predict(x)

# Calculate the accuracy of the classifier
accuracy = accuracy_score(y, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.336283185840708
